### ISSUE TITLE
Planted strawberries still don't seem to be growing

### ISSUE THREAD

**Issue by adozenlionsroaring** [jayhillx/MysticsBiomes#14]
When I plant strawberries, the bushes don't seem to grow, despite waiting several Minecraft days. I've tried planting on both grass and farmland without luck. The patch notes state that this issue was fixed in v3.1.4 in early November, but for me the issue is still occurring on both v3.1.4 and the recently uploaded v3.1.5 (I'm using 1.20.1 Forge). Could this possibly be because I also have Serene Seasons installed? Oh also, it'd be really cool if the strawberry bush growth could be sped up with bone meal.

(Aside from this issue though, awesome mod! It's definitely one of the best biome mods out there - I love the emphasis on colourful environments.)

**Comment by jayhillx** [comment]
oh geez sorry about that! i made them grow slower to combat how common they are in strawberry fields, but i'm starting to think they're a little too slow haha! i also prevented bonemeal working on them because of the sweet strawberries. they're essentially golden apples so being able to farm something like that endlessly is a little op. with serene seasons, the only way i could see that causing some issues is if it like actually changes a biomes coded temperature for each season.

i'll start thinking of some ways to rebalance it all, thanks for telling me! :)

also thank you so much, that seriously means a lot to me :')

**Comment by jayhillx** [comment]
hello! sorry its been a while, i have made changes a while back to the strawberry bush functionalities. these changes will be a part of the 3.2 update in march! :)
